"""create_index for employees_job

Revision ID: 3cfee4ec2d66
Revises: b8efef98600a
Create Date: 2021-06-30 11:43:30.004712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cfee4ec2d66'
down_revision = 'b8efef98600a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_employees_job'), 'employees', ['job'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_job'), table_name='employees')
    # ### end Alembic commands ###
