"""Added year_founded to Company

Revision ID: cf5a62cdff0f
Revises:
Create Date: 2021-06-29 18:14:58.744659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5a62cdff0f'
down_revision = None
branch_labels = None
depends_on = None
'''
None - т.к. первая миграция, затем будут выстрена цепочка
'''


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column(
                  'year_founded',
                  sa.Integer(),
                  nullable=True,
                  postgresql_using='year_founded::integer'
                  ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'currency')
    # ### end Alembic commands ###
